Rewrite newgis script to catch errors. Attempts to automate the db drop can failed due to connected users.

diff --git a/util/newgis b/util/newgis
--- a/util/newgis
+++ b/util/newgis
@@ -5,10 +5,21 @@
 . ./params
 TESTPSQL="psql -h $TESTHOST -U $TESTUSER -p $TESTPORT -d $TESTDB"
 TESTCONN="-h $TESTHOST -U $TESTUSER -p $TESTPORT"
+
 # TODO psql handles TESTDB being a URI; drop/create needs another approach.
-set -x
-dropdb $TESTCONN $TESTDB
-set -e
+
+# Only try to drop the database if it's already there, and catch if drop fails
+MATCHES=`$TESTPSQL -Atqc "SELECT count(*) FROM pg_database WHERE datname='$TESTDB'"`
+if [ "$MATCHES" -gt 0 ] ; then
+  dropdb $TESTCONN $TESTDB
+  ERROR=$?
+  if [ "$ERROR" -gt 0 ] ; then
+    echo Error dropping database, probably connected users, exiting
+    exit 1
+  fi
+fi
+
+set -ex
 createdb $TESTCONN $TESTDB
 $TESTPSQL -c "create extension pg_stat_statements"
 $TESTPSQL -c "create extension pg_buffercache"
